######################
#--------------------#
# QuickshopUI config #
#--------------------#
######################

locations:
  # template
  # x=0.0
  # y=0.0
  # z=0.0
  # world="world"
  # yaw=180.0
  # pitch=180.0