api-version: 1.16
author: CacTt4ck
name: QuickshopUI
main: com.cactt4ck.qsui.Main
version: 1.0.0
depend:
  - Vault
  - QuickShop

commands:
  pshop:
    description: Commande de base du plugin.
    usage: /pshop
    permission: qsui.pshop

permissions:
  qsui.pshop:
    description: Autorise le joueur à utiliser /pshop.
    default: true
  qsui.pshop.setwarp:
    description: Autorise le joueur à utiliser /pshop setwarp.
    default: true
  qsui.pshop.delwarp:
    description: Autorise le joueur à utiliser /pshop delwarp.
    default: true